[package]
name = "dv_server"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
description = "A centralized, modern, data managing and sharing solution"
license = "GPLv3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
diesel = { version = "1.4.6", features = ["postgres","r2d2"] }
dotenv = "0.15.0"
env_logger = "0.8.3"
r2d2 = "0.8.9"
serde = "1.0.124"
thiserror = "1.0.24"
